using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace PortfolioSite {
    public partial class Contact : System.Web.UI.Page {
        protected void Page_Load(object sender, EventArgs e) {

        }

        private void Page_Error(object sender, EventArgs e) {
            // Get last error from the server
            Exception exc = Server.GetLastError();

            // Handle exceptions generated by Button 1
            if (exc is InvalidOperationException) {
                // Pass the error on to the Generic Error page
                Server.Transfer("GenericErrorPage.aspx", true);
            } else if (exc is ArgumentOutOfRangeException) {
                // Handle exceptions generated by Button 2
                // Give the user some information, but
                // stay on the default page
                Response.Write("<h2>Default Page Error</h2>\n");
                Response.Write("<p>Provide as much information here as is " + "appropriate to show to the client.</p>\n");
                Response.Write("Return to the <a href='Default.aspx'>" + "Default Page</a>\n");

                // Log the exception and notify system operators
                //ExceptionUtility.LogException(exc, "DefaultPage");
                //ExceptionUtility.NotifySystemOps(exc);

                // Clear the error from the server
                Server.ClearError();
            } else {
                // Pass the error on to the default global handler
            }
        }

        protected void SendButton_Click(object sender, EventArgs e) {

            Debug.WriteLine("Email: " + inputEmail1.Text);
            Debug.WriteLine("Full name: " + inputName1.Text);
            Debug.WriteLine("Message: " + textareaMessage1.Text);

            Response.Redirect(PageUtils.getPageLink("contact"), false);
        }
    }
}